import './globals.css'
import styles from './layout.module.scss';
import { Inter } from 'next/font/google'
import Image from 'next/image'

const inter = Inter({ subsets: ['latin'] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <header className={styles.header}>
          <div className={styles.headerContainer}>
            <Image
              src="/icons/logo.svg"
              width={41}
              height={41}
              alt="Linkedin logo"
            />
          </div>
        </header>
        {children}
      </body>
    </html>
  )
}
